### ISSUE TITLE
missing env file 

### ISSUE THREAD

**Issue by bazickoff** [a-e-e-collier/fronter_runner#1]
hi the source code missing env file 

what value should put here ?

const ACCOUNT = process.env.REACT_APP_ACCOUNT
const TOKEN_ADDRESS = process.env.REACT_APP_TOKEN_ADDRESS
const EXCHANGE_ADDRESS = process.env.REACT_APP_EXCHANGE_ADDRESS
const ETH_AMOUNT = process.env.REACT_APP_ETH_AMOUNT

**Comment by a-e-e-collier** [comment]
Hi there,&nbsp;&nbsp;Thanks for reaching out, most of the information you should be able to provide following the .readme.md , the only thing that is not explained in there is the exchange address which is the router address for the exchange you are using, ie. uniswap , pancakeswap, quickswap, spiritswap, etc… please be sure to use the checksum for the address.&nbsp;&nbsp;All the best and happy hunting.&nbsp;&nbsp;As ever,&nbsp;&nbsp;Adam Collier&nbsp;Sent From CTemplar Secure Email---------- Original Message ----------On Sun, October 31, 2021 at 9:49 AM, ***@***.***&gt; wrote:&nbsp;&nbsp;hi the source code missing env filewhat value should put here ?const ACCOUNT = process.env.REACT_APP_ACCOUNTconst TOKEN_ADDRESS = process.env.REACT_APP_TOKEN_ADDRESSconst EXCHANGE_ADDRESS = process.env.REACT_APP_EXCHANGE_ADDRESSconst ETH_AMOUNT = process.env.REACT_APP_ETH_AMOUNT—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.&nbsp;&nbsp;
